### PR TITLE
Utilize serviceValidate endpoint available on CAS 3.0

### PR DESCRIPTION
**Pull request by nelsonw2014**
New Dependency (xmltodict)
Tested on Python 3.4.3, should be backwards compatible... needs to be tested in multiple environments

### CODE REVIEW

**Comment by nelsonw2014** [comment]
#26 is referencing this

**Comment by cameronbwhite** [comment]
Thanks! :+1: thanks for the tests too. Give me a bit to look over it and test it against a real server.

**Comment by nelsonw2014** [comment]
No problem

**Comment by cameronbwhite** [comment]
Why did you change `CAS_USERNAME_SESSION_KEY` to `CAS_USER_SESSION_KEY`? I would rather not change this unless needed because it would break builds that upgrade.

**Comment by nelsonw2014** [comment]
It was because the key contains both the username and the attributes dictionary now. I can turn it back if you prefer.

**Comment by cameronbwhite** [comment]
Oh OK. Don't change it back yet Ill think about it more.

**Comment by cameronbwhite** [comment]
@nelsonw2014 So your changes replace `validate` with `serviceValidate` will this break for people using an older version of CAS. Should be concerned with this and if it is how should we handle the problem. Maybe a configuration option to select which one the user wants?

Also we could have `CAS_USERNAME_SESSION_KEY` and `CAS_ATTRIBUTES_SESSION_KEY`.

**Comment by nelsonw2014** [comment]
This will break for CAS servers below version 2.0 as /serviceValidate was introduced then. I'm not sure how back that goes... from the announcements mail list it appears to be back before 2007 though could be way further than that. The last archived message was describing CAS 3.4.7 (2007-03-15).

I wouldn't be very trusting of a CAS server much older than that. The only place I could see it being used is older educational IT infrastructure.

**Comment by nelsonw2014** [comment]
https://github.com/Jasig/cas/releases/tag/v3.0.1-M1 In 2005 they were at version v3.0.1

**Comment by cameronbwhite** [comment]
I think I will bump it to 1.0.0 then after this change then. I do like the idea of having a session key for attributes and the username. That way as little as possible will break.

**Comment by nelsonw2014** [comment]
All done. :+1:

**Comment by cameronbwhite** [comment]
Thanks your code is in https://pypi.python.org/pypi/Flask-CAS/1.0.0

**Pull request merged**
